# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FMain.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2016, 1035)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Lbl_Wt = QtWidgets.QLabel(self.centralwidget)
        self.Lbl_Wt.setGeometry(QtCore.QRect(840, 20, 951, 251))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(160)
        font.setBold(True)
        font.setWeight(75)
        self.Lbl_Wt.setFont(font)
        self.Lbl_Wt.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(101,174,74)")
        self.Lbl_Wt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lbl_Wt.setObjectName("Lbl_Wt")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1800, 50, 101, 211))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(120)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 220, 131, 62))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 320, 101, 62))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.Lne_Pail = QtWidgets.QLineEdit(self.centralwidget)
        self.Lne_Pail.setEnabled(False)
        self.Lne_Pail.setGeometry(QtCore.QRect(140, 310, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        self.Lne_Pail.setFont(font)
        self.Lne_Pail.setObjectName("Lne_Pail")
        self.Lne_PailWt = QtWidgets.QLineEdit(self.centralwidget)
        self.Lne_PailWt.setEnabled(False)
        self.Lne_PailWt.setGeometry(QtCore.QRect(490, 310, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        self.Lne_PailWt.setFont(font)
        self.Lne_PailWt.setObjectName("Lne_PailWt")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(380, 320, 111, 62))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.Txe_Recode = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Txe_Recode.setEnabled(False)
        self.Txe_Recode.setGeometry(QtCore.QRect(140, 680, 1251, 181))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        self.Txe_Recode.setFont(font)
        self.Txe_Recode.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.Txe_Recode.setObjectName("Txe_Recode")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(30, 730, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 610, 121, 62))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.Lne_Note = QtWidgets.QLineEdit(self.centralwidget)
        self.Lne_Note.setEnabled(False)
        self.Lne_Note.setGeometry(QtCore.QRect(140, 600, 611, 62))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        self.Lne_Note.setFont(font)
        self.Lne_Note.setObjectName("Lne_Note")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(20, 410, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(10, 500, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(390, 410, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.Lne_Material = QtWidgets.QLineEdit(self.centralwidget)
        self.Lne_Material.setEnabled(False)
        self.Lne_Material.setGeometry(QtCore.QRect(140, 400, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        self.Lne_Material.setFont(font)
        self.Lne_Material.setAlignment(QtCore.Qt.AlignCenter)
        self.Lne_Material.setObjectName("Lne_Material")
        self.Lne_ActError = QtWidgets.QLineEdit(self.centralwidget)
        self.Lne_ActError.setEnabled(False)
        self.Lne_ActError.setGeometry(QtCore.QRect(1590, 840, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        self.Lne_ActError.setFont(font)
        self.Lne_ActError.setStyleSheet("color:rgb(191,31,31)")
        self.Lne_ActError.setAlignment(QtCore.Qt.AlignCenter)
        self.Lne_ActError.setObjectName("Lne_ActError")
        self.Lne_PreError = QtWidgets.QLineEdit(self.centralwidget)
        self.Lne_PreError.setEnabled(False)
        self.Lne_PreError.setGeometry(QtCore.QRect(490, 400, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        self.Lne_PreError.setFont(font)
        self.Lne_PreError.setAlignment(QtCore.Qt.AlignCenter)
        self.Lne_PreError.setObjectName("Lne_PreError")
        self.Lne_MaterialWt = QtWidgets.QLineEdit(self.centralwidget)
        self.Lne_MaterialWt.setEnabled(False)
        self.Lne_MaterialWt.setGeometry(QtCore.QRect(140, 490, 611, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        self.Lne_MaterialWt.setFont(font)
        self.Lne_MaterialWt.setAlignment(QtCore.Qt.AlignCenter)
        self.Lne_MaterialWt.setObjectName("Lne_MaterialWt")
        self.Lne_Formule = QtWidgets.QLineEdit(self.centralwidget)
        self.Lne_Formule.setEnabled(False)
        self.Lne_Formule.setGeometry(QtCore.QRect(140, 220, 611, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        self.Lne_Formule.setFont(font)
        self.Lne_Formule.setObjectName("Lne_Formule")
        self.Btn_Weigh = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Weigh.setGeometry(QtCore.QRect(20, 980, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        self.Btn_Weigh.setFont(font)
        self.Btn_Weigh.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.Btn_Weigh.setObjectName("Btn_Weigh")
        self.Btn_Closed = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Closed.setGeometry(QtCore.QRect(1700, 980, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        self.Btn_Closed.setFont(font)
        self.Btn_Closed.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.Btn_Closed.setObjectName("Btn_Closed")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 131, 62))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.Lne_QR = QtWidgets.QLineEdit(self.centralwidget)
        self.Lne_QR.setEnabled(True)
        self.Lne_QR.setGeometry(QtCore.QRect(140, 30, 611, 62))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        self.Lne_QR.setFont(font)
        self.Lne_QR.setText("")
        self.Lne_QR.setObjectName("Lne_QR")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 900, 1371, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.progressBar.setFont(font)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("border: 2px solid grey;   border-radius: 5px;   text-align: center;")
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 110, 701, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(70)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(750, 510, 51, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(232, 232, 232)")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.Btn_Keyboard = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Keyboard.setGeometry(QtCore.QRect(1500, 980, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        self.Btn_Keyboard.setFont(font)
        self.Btn_Keyboard.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.Btn_Keyboard.setObjectName("Btn_Keyboard")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1430, 330, 451, 451))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color:rgb(3, 41, 81)")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 431, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Btn_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_1.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_1.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_1.setFont(font)
        self.Btn_1.setObjectName("Btn_1")
        self.horizontalLayout_3.addWidget(self.Btn_1)
        self.Btn_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_2.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_2.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_2.setFont(font)
        self.Btn_2.setObjectName("Btn_2")
        self.horizontalLayout_3.addWidget(self.Btn_2)
        self.Btn_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_3.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_3.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_3.setFont(font)
        self.Btn_3.setObjectName("Btn_3")
        self.horizontalLayout_3.addWidget(self.Btn_3)
        self.Btn_Switch = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_Switch.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_Switch.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Switch.setFont(font)
        self.Btn_Switch.setObjectName("Btn_Switch")
        self.horizontalLayout_3.addWidget(self.Btn_Switch)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Btn_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_4.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_4.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_4.setFont(font)
        self.Btn_4.setObjectName("Btn_4")
        self.horizontalLayout_2.addWidget(self.Btn_4)
        self.Btn_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_5.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_5.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_5.setFont(font)
        self.Btn_5.setObjectName("Btn_5")
        self.horizontalLayout_2.addWidget(self.Btn_5)
        self.Btn_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_6.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_6.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_6.setFont(font)
        self.Btn_6.setObjectName("Btn_6")
        self.horizontalLayout_2.addWidget(self.Btn_6)
        self.Btn_Backspace = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_Backspace.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_Backspace.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Backspace.setFont(font)
        self.Btn_Backspace.setObjectName("Btn_Backspace")
        self.horizontalLayout_2.addWidget(self.Btn_Backspace)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Btn_7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_7.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_7.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_7.setFont(font)
        self.Btn_7.setObjectName("Btn_7")
        self.horizontalLayout_5.addWidget(self.Btn_7)
        self.Btn_8 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_8.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_8.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_8.setFont(font)
        self.Btn_8.setObjectName("Btn_8")
        self.horizontalLayout_5.addWidget(self.Btn_8)
        self.Btn_9 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_9.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_9.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_9.setFont(font)
        self.Btn_9.setObjectName("Btn_9")
        self.horizontalLayout_5.addWidget(self.Btn_9)
        self.Btn_Enter = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_Enter.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_Enter.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Enter.setFont(font)
        self.Btn_Enter.setObjectName("Btn_Enter")
        self.horizontalLayout_5.addWidget(self.Btn_Enter)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Btn_Point = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_Point.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_Point.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Point.setFont(font)
        self.Btn_Point.setObjectName("Btn_Point")
        self.horizontalLayout_4.addWidget(self.Btn_Point)
        self.Btn_0 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_0.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_0.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_0.setFont(font)
        self.Btn_0.setObjectName("Btn_0")
        self.horizontalLayout_4.addWidget(self.Btn_0)
        self.Btn_Hyphen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_Hyphen.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_Hyphen.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Hyphen.setFont(font)
        self.Btn_Hyphen.setObjectName("Btn_Hyphen")
        self.horizontalLayout_4.addWidget(self.Btn_Hyphen)
        self.Btn_Hide = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_Hide.setMinimumSize(QtCore.QSize(102, 95))
        self.Btn_Hide.setMaximumSize(QtCore.QSize(102, 95))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Hide.setFont(font)
        self.Btn_Hide.setObjectName("Btn_Hide")
        self.horizontalLayout_4.addWidget(self.Btn_Hide)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.Btn_Login = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Login.setGeometry(QtCore.QRect(1290, 980, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        self.Btn_Login.setFont(font)
        self.Btn_Login.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.Btn_Login.setObjectName("Btn_Login")
        self.Grp_Warning = QtWidgets.QGroupBox(self.centralwidget)
        self.Grp_Warning.setGeometry(QtCore.QRect(770, 380, 631, 221))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Grp_Warning.setFont(font)
        self.Grp_Warning.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.Grp_Warning.setObjectName("Grp_Warning")
        self.Lbl_Warning = QtWidgets.QLabel(self.Grp_Warning)
        self.Lbl_Warning.setGeometry(QtCore.QRect(80, 70, 511, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.Lbl_Warning.setFont(font)
        self.Lbl_Warning.setStyleSheet("color:rgb(3, 41,81)")
        self.Lbl_Warning.setAlignment(QtCore.Qt.AlignCenter)
        self.Lbl_Warning.setObjectName("Lbl_Warning")
        self.Btn_Warning = QtWidgets.QPushButton(self.Grp_Warning)
        self.Btn_Warning.setGeometry(QtCore.QRect(210, 160, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.Btn_Warning.setFont(font)
        self.Btn_Warning.setStyleSheet("color:rgb(3, 41,81)")
        self.Btn_Warning.setObjectName("Btn_Warning")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1820, 910, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(750, 430, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(232, 232, 232)")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1820, 840, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_12.setObjectName("label_12")
        self.Lne_MaterialWt_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Lne_MaterialWt_2.setEnabled(False)
        self.Lne_MaterialWt_2.setGeometry(QtCore.QRect(1590, 900, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        self.Lne_MaterialWt_2.setFont(font)
        self.Lne_MaterialWt_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Lne_MaterialWt_2.setObjectName("Lne_MaterialWt_2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(750, 350, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(232, 232, 232)")
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(1440, 840, 131, 62))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(1440, 900, 131, 62))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(249,,237,236);\n"
"color:rgb(3,41,81)")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "高精度配料系统"))
        self.Lbl_Wt.setText(_translate("MainWindow", "3000"))
        self.label_2.setText(_translate("MainWindow", "g"))
        self.label_6.setText(_translate("MainWindow", "工 位 号"))
        self.label_7.setText(_translate("MainWindow", "罐     类"))
        self.label_10.setText(_translate("MainWindow", "罐   重"))
        self.label_16.setText(_translate("MainWindow", "充 装 记 录"))
        self.label_17.setText(_translate("MainWindow", "备         注"))
        self.label_18.setText(_translate("MainWindow", "介质编码"))
        self.label_19.setText(_translate("MainWindow", "目标重量"))
        self.label_20.setText(_translate("MainWindow", "设置误差"))
        self.Btn_Weigh.setText(_translate("MainWindow", "称重完成"))
        self.Btn_Closed.setText(_translate("MainWindow", "关机"))
        self.label_8.setText(_translate("MainWindow", "手动输入"))
        self.label_9.setText(_translate("MainWindow", "Z-FWeigh"))
        self.label_3.setText(_translate("MainWindow", "g"))
        self.Btn_Keyboard.setText(_translate("MainWindow", "手动输入"))
        self.Btn_1.setText(_translate("MainWindow", "1"))
        self.Btn_2.setText(_translate("MainWindow", "2"))
        self.Btn_3.setText(_translate("MainWindow", "3"))
        self.Btn_Switch.setText(_translate("MainWindow", "Switch\n"
"交换"))
        self.Btn_4.setText(_translate("MainWindow", "4"))
        self.Btn_5.setText(_translate("MainWindow", "5"))
        self.Btn_6.setText(_translate("MainWindow", "6"))
        self.Btn_Backspace.setText(_translate("MainWindow", "Back\n"
"Spcae\n"
"回格"))
        self.Btn_7.setText(_translate("MainWindow", "7"))
        self.Btn_8.setText(_translate("MainWindow", "8"))
        self.Btn_9.setText(_translate("MainWindow", "9"))
        self.Btn_Enter.setText(_translate("MainWindow", "Enter\n"
"回车"))
        self.Btn_Point.setText(_translate("MainWindow", "."))
        self.Btn_0.setText(_translate("MainWindow", "0"))
        self.Btn_Hyphen.setText(_translate("MainWindow", "—"))
        self.Btn_Hide.setText(_translate("MainWindow", "Hide\n"
"隐藏"))
        self.Btn_Login.setText(_translate("MainWindow", "切换用户"))
        self.Grp_Warning.setTitle(_translate("MainWindow", "警告"))
        self.Lbl_Warning.setText(_translate("MainWindow", "警告内容"))
        self.Btn_Warning.setText(_translate("MainWindow", "确定"))
        self.label_4.setText(_translate("MainWindow", "g"))
        self.label_11.setText(_translate("MainWindow", "g"))
        self.label_12.setText(_translate("MainWindow", "g"))
        self.label_13.setText(_translate("MainWindow", "g"))
        self.label_14.setText(_translate("MainWindow", "当前误差"))
        self.label_15.setText(_translate("MainWindow", "当前重量"))
